import React from 'react';
import '../styles/AISummaryView.css';

/**
 * AI Summary View component - Shows an AI-generated summary of top articles
 * Displays a clean panel with summary, sentiment analysis, and key highlights
 */
const AISummaryView = ({ articles = [] }) => {
  // Get the top 3 articles for summarization
  const topArticles = articles.slice(0, 3);
  
  // Sample sentiment analysis (would be replaced by actual API call in production)
  const getSentiment = () => {
    const sentiments = ['Positive', 'Neutral', 'Negative'];
    return sentiments[Math.floor(Math.random() * sentiments.length)];
  };
  
  // Determine overall sentiment based on the top articles
  const overallSentiment = getSentiment();
  
  // Get sentiment class for styling
  const getSentimentClass = (sentiment) => {
    switch(sentiment) {
      case 'Positive':
        return 'sentiment-positive';
      case 'Negative':
        return 'sentiment-negative';
      default:
        return 'sentiment-neutral';
    }
  };
  
  // Generate sample highlights (would be replaced by actual AI generation)
  const generateHighlights = (articles) => {
    if (!articles || articles.length === 0) {
      return ['No articles available for summarization'];
    }
    
    // Create highlights based on article titles
    return articles.map(article => 
      article.title ? 
        `Key insight: ${article.title.split(' ').slice(0, 5).join(' ')}...` : 
        'Unable to generate highlight'
    );
  };
  
  const highlights = generateHighlights(topArticles);
  
  return (
    <div className="ai-summary-view glass-panel">
      <div className="summary-header">
        <h2>AI News Summary</h2>
        <div className={`sentiment-badge ${getSentimentClass(overallSentiment)}`}>
          {overallSentiment}
        </div>
      </div>
      
      <div className="summary-content">
        <p className="summary-text">
          {topArticles.length > 0 ? (
            `Today's news focuses on ${topArticles[0]?.title?.split(' ').slice(0, 3).join(' ') || 'current events'}, 
            with developments in ${topArticles[1]?.title?.split(' ').slice(0, 2).join(' ') || 'various sectors'} 
            and implications for ${topArticles[2]?.title?.split(' ').slice(0, 2).join(' ') || 'global affairs'}.`
          ) : (
            'No articles available for summarization.'
          )}
        </p>
        
        <div className="summary-highlights">
          <h3>What You Need to Know</h3>
          <ul>
            {highlights.map((highlight, index) => (
              <li key={index} className="highlight-item">
                <span className="highlight-bullet">•</span>
                <span className="highlight-text">{highlight}</span>
              </li>
            ))}
          </ul>
        </div>
      </div>
      
      <div className="summary-footer">
        <div className="ai-attribution">
          <div className="ai-icon">
            <span className="ai-pulse"></span>
          </div>
          <span>Generated by AI • Updated just now</span>
        </div>
      </div>
    </div>
  );
};

export default AISummaryView;